# ROS-standard
IMU:        {topic: /gt_box/cpt7/gps/imu,                 frame_id: cpt7_imu}
RAWIMU:     {topic: /gt_box/cpt7/imu/data_raw,            frame_id: cpt7_imu}
GPSFix:     {topic: /gt_box/cpt7/gps/gps,                 frame_id: gps}
NavSatFix:  {topic: /gt_box/cpt7/gps/fix,                 frame_id: gps} 
Odometry:   {topic: /gt_box/cpt7/odom,       frame_id: cpt7_odom} 

# Oem7-specific 
Oem7RawMsg:    {topic: /gt_box/cpt7/oem7raw,    frame_id: gps, queue_size: "200"}
BESTGNSSPOS:   {topic: /gt_box/cpt7/bestgnsspos,    frame_id: gps}
BESTPOS:    {topic: /gt_box/cpt7/bestpos,    frame_id: gps}
BESTUTM:    {topic: /gt_box/cpt7/bestutm,    frame_id: gps}
BESTVEL:    {topic: /gt_box/cpt7/bestvel,    frame_id: gps}
PPPPOS:     {topic: /gt_box/cpt7/ppppos,     frame_id: gps}
TERRASTARINFO:   {topic: /gt_box/cpt7/terrastarinfo,    frame_id: gps}
TERRASTARSTATUS: {topic: /gt_box/cpt7/terrastarstatus,  frame_id: gps}
CORRIMU:    {topic: /gt_box/cpt7/corrimu,    frame_id: gps}
HEADING2:   {topic: /gt_box/cpt7/heading2,   frame_id: gps}
INSPVA:     {topic: /gt_box/cpt7/inspva,     frame_id: gps}
INSPVAX:    {topic: /gt_box/cpt7/inspvax,    frame_id: gps,  queue_size: "10"}
INSSTDEV:   {topic: /gt_box/cpt7/insstdev,   frame_id: gps,  queue_size: "10"}
INSCONFIG:  {topic: /gt_box/cpt7/insconfig,  frame_id: gps,  queue_size: "10"}
RXSTATUS:   {topic: /gt_box/cpt7/rxstatus,   frame_id: gps,  queue_size: "10"}
TIME:       {topic: /gt_box/cpt7/time,       frame_id: gps} 


